### ISSUE TITLE
Why forcing some plugins to versions < 1.5 ?

### ISSUE THREAD

**Issue by DjebbZ** [monokrome/brunch-with-brunch#1]
Question from a guy who didn't not at follow everything related to Brunch. `javascript-brunch` and `css-brunch` for instance have been updated to 1.5 during January 2013. Is there a specific reason ?

**Comment by monokrome** [comment]
I try to follow brunch-with-chaplin, since it's fairly well maintained. Since chaplin is now using 1.6, I have updated this project accordingly.

Thanks for making me aware of this.
